### ISSUE TITLE
Allow to propose a takeback

### ISSUE THREAD

**Issue by programarivm** [chesslablab/chess-server#36]
A new method to allow proposing a takeback should be implemented in the `Chess\Game` class as described in https://github.com/chesslablab/php-chess/issues/55.

As you may have noted, there's a one-to-one correspondence between the `Chess\Game` methods described in the PHP Chess docs and the commands available in the chess server:

`ascii(): string` <-> `ChessServer\Command\AsciiCommand.php`
`captures(): array` <-> `ChessServer\Command\CapturesCommand.php`
`castling(): ?array` <-> `ChessServer\Command\CastlingCommand.php`
...

However, the `ChessServer\Command\TakebackCommand.php` is missing. 

The missing file should be added once the takeback method has been implemented in `Chess\Game`.

Also see https://github.com/chesslablab/redux-chess/issues/132.

**Comment by programarivm** [comment]
The [`undoMove()`](https://php-chess.readthedocs.io/en/latest/game-methods/#undomove) should be fixed; the server crashes if undoing more moves than the existing ones.

```
$ php cli/ws-server.php 
Welcome to PHP Chess Server
Commands available:
/accept {"id":"id"} Accepts a friend request to play a game.
/ascii Prints the ASCII representation of the game.
/castling Gets the castling status.
/captures Gets the pieces captured by both players.
/fen Prints the FEN string representation of the game.
/heuristicpicture Takes a balanced heuristic picture of the current game.
/history The current game's history.
/ischeck Finds out if the game is in check.
/ismate Finds out if the game is over.
/piece {"position":"string"} Gets a piece by its position on the board.
/pieces {"color":["w","b"]} Gets the pieces on the board by color.
/playfen {"fen":"string"} Plays a chess move in shortened FEN format.
/quit Quits a game.
/start {"mode":["analysis","loadfen","playfriend"],"fen":"string","color":["w","b"],"min":"int"} Starts a new game.
/status The current game status.
/undomove Undoes the last move.

Listening to commands...
PHP Notice:  Trying to get property 'move' of non-object in /home/standard/projects/chess-server/vendor/chesslablab/php-chess/src/Board.php on line 719
PHP Notice:  Trying to get property 'position' of non-object in /home/standard/projects/chess-server/vendor/chesslablab/php-chess/src/Board.php on line 719
PHP Notice:  Trying to get property 'next' of non-object in /home/standard/projects/chess-server/vendor/chesslablab/php-chess/src/Board.php on line 719
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Chess\Board::getPieceByPosition() must be of the type string, null given, called in /home/standard/projects/chess-server/vendor/chesslablab/php-chess/src/Board.php on line 719 and defined in /home/standard/projects/chess-server/vendor/chesslablab/php-chess/src/Board.php:361
Stack trace:
#0 /home/standard/projects/chess-server/vendor/chesslablab/php-chess/src/Board.php(719): Chess\Board->getPieceByPosition()
#1 /home/standard/projects/chess-server/vendor/chesslablab/php-chess/src/Game.php(348): Chess\Board->undoMove()
#2 /home/standard/projects/chess-server/src/GameMode/AbstractMode.php(127): Chess\Game->undoMove()
#3 /home/standard/projects/chess-server/src/Socket.php(94): ChessServer\GameMode\AbstractMode->res()
#4 /home/standard/projects/chess-server/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php(75): ChessServer\Socket->onMessage()
#5 /home/standard/projects/chess-server/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php(131): Ratchet\WebSocket\WsSer in /home/standard/projects/chess-server/vendor/chesslablab/php-chess/src/Board.php on line 361
```

```
$ websocat ws://localhost:8080
/start analysis
{"\/start":{"mode":"analysis"}}
/playfen "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b"
{"\/playfen":{"turn":"w","legal":true,"check":false,"mate":false,"movetext":"1.e4","fen":"rnbqkbnr\/pppppppp\/8\/8\/4P3\/8\/PPPP1PPP\/RNBQKBNR b KQkq e3"}}
/undomove
{"\/undomove":null}
/playfen "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b"
{"\/playfen":{"turn":"w","legal":true,"check":false,"mate":false,"movetext":"1.e4","fen":"rnbqkbnr\/pppppppp\/8\/8\/4P3\/8\/PPPP1PPP\/RNBQKBNR b KQkq e3"}}
/undomove
{"\/undomove":null}
/undomove
```

**Comment by programarivm** [comment]
Merged PR https://github.com/chesslablab/chess-server/pull/37
